vault_password: ENC[AES256_GCM,data:eUCbPTO35SjSN6grOaiPnQ3Q8P07JTrNdjnJphUPdkqGZGo4akfwtqm2oyVPEpIN,iv:BKr0c4D1EA0SIJr9Js+b+A9j0WUmqbrEL7cble4nskk=,tag:tlJ7dpXGXeVG7m02nyCdNg==,type:str]
sops:
    lastmodified: "2026-07-08T13:00:58Z"
    mac: ENC[AES256_GCM,data:+xVULGSiUBohWXwtqHaeVQ2UluTa68f1LflfGIJUP1tzj2TyYN7vyuVTnOt9Ut4WL7fSQvSjIj1O4G3MxFw4x6InXOqhDvEtukPeM8Ab5/G/QIgxZqdWvQ30yCPnPeKKzht20P1dUH9/N2a8cSo6bq5HtU0QN63PQtu7XjtPphs=,iv:Kkpl6PvV4MfL3k2vHwNb7hSMqwynl/8yqsVv9yGV0JA=,tag:hDLDNsJwn2gUcKNeoZrrhw==,type:str]
    pgp:
        - created_at: "2026-07-08T13:00:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxyDW9+TKoYsAQ//ckUAXrs9Wjzy0HIiKLhlOsHZpToyxKuQ/VW0nxdKUrcM
            z0Q8RhFl2OQ6l6OrHygoyotNymet4bnqo4VsV3FvwuwvjTZu8stzP7YEq5chUD0z
            G1bucHp2sC1ttqZz1ItzGUnhl9k72gdSC9hnH8mYdDX+EVIObOUspyqT+CnqXY2c
            tYl+983bf6M8ozKroM/8+ym6OJANhBvsxlp9INIFJGKIGd6ne8q6LAbS7GaxbrQm
            Rfn0yMK0PsrghA2FiqSGgoy50rVVYeDYCIJz3ek/iOc1IriRsbZg/XfvqsfvFnnH
            tdkqWTNXZrsrxaGin2Nr/r32jupJU5DSwY6R0gVrXAW4xXJFec/D0g5Oke8gOpUd
            PyZQ4F30NdL7884bdtc2GMJA5YVF2gl6+69YRZDCvLXKZUg5XWpr1d/ZUth/Cn4s
            H4dsJgWjT4tyP0mBQluxt1W/SgCJKtPphqC4aEtSEFe5XkuCVaUFoVPTPdSYDzSY
            Q6P5KfE+2g3a5KGfv8r/fTalm4Mr0We4hylsa4kmprzySYH6pUUnYoURLtIc7GfA
            WLH/xEFLmprgcGYz2WGcQjNBsWAQD6pxUVviVnffIZeWHxX+C3s56HXReRDzl4ew
            VCFMsj6SpO0UJ1DxPIooGoLgBm/kAUTbxyy1uLmHT7fQueJsR6HnpCyI9+obMYzS
            XgGKd/jRf6fD9Yul+S4FHVx7Ifw+3gbt1KXNkinoyZUwv0Nw6cYq+3QCrQV3ud8l
            /1k8Z/9ytTqeE7JQE7tHhsMkTNlw5ZOdo0Ai6s3s6hVf/mZ9bNmKNXcWq4qzGJo=
            =AQcQ
            -----END PGP MESSAGE-----
          fp: 089D27EE8E61BDC0C3F3C58CA03F69C42E8025A3
    unencrypted_suffix: _unencrypted
    version: 3.13.2
